### ISSUE TITLE
beforeEach assertion should explain itself

### ISSUE THREAD

**Issue by mightyiam** [bahmutov/cypress-watch-and-reload#10]
Thank you for this plugin.

It took me a while to figure out the origin of this `beforeEach` assertion.

![Screenshot from 2019-03-23 10-47-11](https://user-images.githubusercontent.com/635591/54863347-f519c880-4d79-11e9-88d7-7d274c41b0a3.png)

Would a log message be appropriate? Something like: "This assertion is generated by the `cypress-watch-and-reload` plugin.".

**Comment by bahmutov** [comment]
Yeah it actually caught me too recently ;) I will change the message - or feel free to submit a pull request
