### ISSUE TITLE
Add button to toggle watch and reload

### ISSUE THREAD

**Issue by unlocomqx** [bahmutov/cypress-watch-and-reload#118]
In TDD, I often need to do small adjustments without restarting the tests. 
In that case, a button to toggle watch and reload would be very handy.

My suggestion is to have a button next to "Disable Auto-scrolling"

<img width="245" alt="2021-08-02 at 12 51 PM" src="https://user-images.githubusercontent.com/793712/127857691-1d9ccada-1765-49e4-9da2-2913e1ce3834.png">

If it's sounds like a good idea, let me know and I'll try to submit a PR for it

Thank you

**Comment by bahmutov** [comment]
Sure, that does sound good

**Comment by unlocomqx** [comment]
Thanks, I'll give it a try, see how it goes
