### ISSUE TITLE
Custom path to config file is not respected

### ISSUE THREAD

**Issue by kalinchernev** [bahmutov/cypress-watch-and-reload#125]
Hi, I spent an hour trying to prepare a pull request for this issue which seemed easy to solve, but couldn't.

This line https://github.com/bahmutov/cypress-watch-and-reload/blob/master/plugins.js#L12 assumes that the config file is always in the root folder from where the process is to be started. This prevents custom configurations from using the plugin.

For example, if I move the `cypress.json` to `cypress/cypress.json` in this repo, the problem will already appear with a different issue of a missing file, but still illustrating the same core problem.

The CLI has these two options

```
  .option('-c, --config <config>', text('config'))
  .option('-C, --config-file <config-file>', text('configFile'))
```

But they are not accessible to plugins.js in the way it's written I think. Checked the plugins API but it's not following 

```js
// export a function
module.exports = (on, config) => {
  // configure plugins here
}
```

I tried also inspecting the `process.argv` before requiring the config file and gives

```
  argv [
  '/homepath/.cache/Cypress/8.2.0/Cypress/Cypress',
  '/homepath/.cache/Cypress/8.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js',
  '--file',
  '/homepath/Projects/cypress-watch-and-reload/cypress/plugins/index.js',
  '--projectRoot',
  '/homepath/Projects/cypress-watch-and-reload'
]
```

Which is not passing what i've initially sent to --config-file argument through `cypress open --config-file cypress/cypress.json `.

With all that i'm not quite sure which way would be easier to go for solving this: 

- Using a native cypress api to get config and use it? https://docs.cypress.io/api/cypress-api/config doesn't suggest this is an api meant to be used outside tests?
- Maybe dig the arguments info from the process in a different way? I checked the CLI and it's spawning a new process and not passing these at the moment i think
- Or rather wrapping current logic in a function and allow for reuse of `config` from plugins api?

```
module.exports = (on, config) => {
  require('cypress-watch-and-reload/plugins')(config)
}
```

**Comment by bahmutov** [comment]
Yeah we should just change it to option 3 to take the config as an argument. It would be a breaking change but not too bad.

**Comment by kalinchernev** [comment]
@bahmutov thank you for the quick feedback! I opened a pull request

**Comment by kalinchernev** [comment]
🎉🎉🎉
