### ISSUE TITLE
Unable to follow the setup instructions when using Cypress 10

### ISSUE THREAD

**Issue by andersr** [bahmutov/cypress-watch-and-reload#171]
I installed the newest version of Cypress and then installed this plugin. However, I am not able to follow the instructions for configuring the plugin in Cypress 10 due to changes in the new version associated with configuration.

Does this plugin work with Cypress 10?  If so, what are the configuration instructions? Thanks!

**Comment by bahmutov** [comment]
https://glebbahmutov.com/blog/cypress-v10-tips/#register-the-plugins
