### ISSUE TITLE
Hi..I want to know if there is way to run spec files which are different folder using pattern 

### ISSUE THREAD

**Issue by minams2** [bahmutov/cypress-watch-and-reload#3]
Hi..I want to know if there is way to run spec files which are different folder using pattern something like ./node_modules/.bin/cypress run --browser chrome --spec '/Users/msomasundaram/git/atlas/cypress/integration/templates/smoke-edit/create.spec.js'

this is error i got
Can't run because no spec files were found.

We searched for any files matching this glob pattern:
![screen shot 2019-03-05 at 10 16 19 pm](https://user-images.githubusercontent.com/36013340/53853798-ef0fa380-3f94-11e9-8959-05b578609ff4.png)

**Comment by bahmutov** [comment]
I think your question is more appropriate for cypress-io/cypress repo, not here
