### ISSUE TITLE
Accept array of strings in options.watch

### ISSUE THREAD

**Issue by gomesalexandre** [bahmutov/cypress-watch-and-reload#34]
Currently, `options.watch` only accepts a string to pass to `chokidar.watch`:

https://github.com/bahmutov/cypress-watch-and-reload/blob/f16580d9808fe1973b7b8fd46d95457340460fa5/plugins.js#L14

It would be nice to also accept an array of strings, as `chokidar.watch` signature is `chokidar.watch(paths, [options])`

This way, we could be more accurate in what we watch for ! 

Another good thing to have would be to handle the second argument `options` of `chokidar.watch` so we can use the [`ignored`](https://github.com/paulmillr/chokidar#path-filtering) key, but that will be the subject of another issue and PR ! 🚀

**Comment by gomesalexandre** [comment]
https://github.com/bahmutov/cypress-watch-and-reload/pull/35

**Comment by unlocomqx** [comment]
A regex works fine for most cases
```
"cypress-watch-and-reload": {
    "watch": "./views/**/*.(ts|tpl|scss)"
 }
```
